{application,simple_cache,
	[
		{discription,"A Simple Cache System"},
		{vsn,"1.0"},
		{modules,[
					simple_cache,
					sc_app,
					sc_sup,
					sc_element_sup,
					sc_store,
					sc_element,
					sc_event,
					sc_event_logger
				 ]
		},
		{registered,[sc_sup]},
		{applications,[kernel,stdlib,mnesia]},
		{mod,{sc_app,[]}}
	]
}.